services:
  mariadb:
    build: ./mariadb/
    container_name: mariadb
    environment:
      MYSQL_WP_DATABASE: wp_database
      MYSQL_WP_USER: wp_user
      MYSQL_WP_PASSWORD_FILE: /run/secrets/mysql_wp_password.txt
    secrets:
      - mysql_wp_password

secrets:
  mysql_wp_password:
    file: ../../secrets/mysql_wp_password.txt

